Repository CSC207-2022F-UofT/course-project-group-80, pull requests merged in 2022-12, with the labels that each got.

#67 Feature 1 user login
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginActivity.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginController.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginInput.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginInteractor.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginPresenter.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginPresenterFormatter.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginViewInterface.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginViewModel.java
  app/src/main/res/layout/loginview.xml
Labels: bug, refactor

#56 Finishes #46: contacts list for chat system
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group80/uoftinder/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/ContactsActivity.java
  app/src/main/java/com/group80/uoftinder/chat/ContactModel.java
  app/src/main/java/com/group80/uoftinder/chat/ContactPresenter.java
  app/src/main/java/com/group80/uoftinder/chat/ContactViewHolder.java
  app/src/main/java/com/group80/uoftinder/chat/ContactsView.java
  app/src/main/java/com/group80/uoftinder/feed/RecommendationView.java
  app/src/main/java/com/group80/uoftinder/firebase/ImageViewImagePresenter.java
  app/src/main/res/layout/activity_contacts.xml
  app/src/main/res/layout/uoftinder_contact_list_contact_layout.xml
Labels: enhancement

#71 Finishes #61: Firebase Firestore Database Access
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group80/uoftinder/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/Constants.java
  app/src/main/java/com/group80/uoftinder/ContactsActivity.java
  app/src/main/java/com/group80/uoftinder/chat/ContactPresenter.java
  app/src/main/java/com/group80/uoftinder/chat/MessageFactory.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountInteractor.java
  app/src/main/java/com/group80/uoftinder/feed/GenerateCompatibilityList.java
  app/src/main/java/com/group80/uoftinder/feed/RecommendationView.java
  app/src/main/java/com/group80/uoftinder/firebase/firestore/FirestoreDbReader.java
  app/src/main/java/com/group80/uoftinder/firebase/firestore/FirestoreDbWriter.java
  app/src/main/res/layout/activity_contacts.xml
  app/src/test/java/com/group80/uoftinder/UserUnitTest.java
Labels: enhancement

#74 72 enhancement 21 profile image upload
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group80/uoftinder/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/ProfilePicUploadActivity.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountActivity.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountInput.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountInteractor.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountPresenter.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountPresenterFormatter.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountPresenterInterface.java
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountViewInterface.java
  app/src/main/java/com/group80/uoftinder/feed/GenerateCompatibilityList.java
  app/src/main/java/com/group80/uoftinder/firebase/ImageViewImagePresenter.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ImageStorageDbController.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginActivity.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginController.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginInteractor.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginPresenter.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginPresenterFormatter.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginPresenterInterface.java
  app/src/main/java/com/group80/uoftinder/login_use_case/LoginViewInterface.java
  app/src/main/java/com/group80/uoftinder/profile_upload/ProfileUploadPresenter.java
  app/src/main/java/com/group80/uoftinder/profile_upload/ProfileUploadView.java
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_profile_upload.xml
  app/src/main/res/layout/basic_info_view.xml
  app/src/main/res/layout/basicinfoview.xml
  app/src/main/res/layout/createaccountview.xml
  app/src/main/res/layout/loginview.xml
  app/src/main/res/layout/questionnaire_academic.xml
  app/src/main/res/layout/questionnaire_friendship.xml
  app/src/main/res/layout/questionnaire_romantic.xml
Labels: bug, enhancement, refactor

#79 Migrate Chat System to MVP
  app/src/main/java/com/group80/uoftinder/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/ContactsActivity.java
  app/src/main/java/com/group80/uoftinder/chat/ChatPresenter.java
  app/src/main/java/com/group80/uoftinder/chat/ChatView.java
  app/src/main/java/com/group80/uoftinder/chat/ContactPresenter.java
  app/src/main/java/com/group80/uoftinder/chat/ContactViewHolder.java
  app/src/main/java/com/group80/uoftinder/chat/ContactsView.java
  app/src/main/java/com/group80/uoftinder/chat/MessageAdapter.java
  app/src/main/java/com/group80/uoftinder/feed/GenerateCompatibilityList.java
  app/src/main/java/com/group80/uoftinder/firebase/realtime/RealtimeDbUploadable.java
  app/src/main/java/com/group80/uoftinder/firebase/realtime/ctRealtimeController.java
Labels: refactor

#85 Finishes #83: Add Profile Image for Recommendation Feed
  app/src/main/java/com/group80/uoftinder/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/chat/ChatView.java
  app/src/main/java/com/group80/uoftinder/chat/ContactViewHolder.java
  app/src/main/java/com/group80/uoftinder/feed/RecommendationView.java
  app/src/main/java/com/group80/uoftinder/firebase/ProfileImagePresenter.java
  app/src/main/java/com/group80/uoftinder/firebase/ProfileImageViewInterface.java
  app/src/main/res/layout/recommendation_profile_display.xml
Labels: bug, enhancement, refactor

#88 Fixes chat room generation that caused chat to malfunction
  app/src/main/java/com/group80/uoftinder/chat/ChatView.java
Labels: bug

#93 Fixes #89: Refactor Chat and Contacts List
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group80/uoftinder/MatchInteractor.java
  app/src/main/java/com/group80/uoftinder/chat/chat/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/chat/chat/ChatPresenter.java
  app/src/main/java/com/group80/uoftinder/chat/chat/ChatView.java
  app/src/main/java/com/group80/uoftinder/chat/chat/Message.java
  app/src/main/java/com/group80/uoftinder/chat/chat/MessageAdapter.java
  app/src/main/java/com/group80/uoftinder/chat/chat/MessageController.java
  app/src/main/java/com/group80/uoftinder/chat/chat/MessageFactory.java
  app/src/main/java/com/group80/uoftinder/chat/contacts_list/ContactModel.java
  app/src/main/java/com/group80/uoftinder/chat/contacts_list/ContactPresenter.java
  app/src/main/java/com/group80/uoftinder/chat/contacts_list/ContactViewHolder.java
  app/src/main/java/com/group80/uoftinder/chat/contacts_list/ContactsActivity.java
  app/src/main/java/com/group80/uoftinder/chat/contacts_list/ContactsView.java
  app/src/main/java/com/group80/uoftinder/feed/GenerateCompatibilityList.java
  app/src/main/java/com/group80/uoftinder/feed/NoNewRecommendation.java
  app/src/main/java/com/group80/uoftinder/feed/RecommendationView.java
  app/src/main/java/com/group80/uoftinder/firebase/ProfileImageViewInterface.java
  app/src/main/java/com/group80/uoftinder/firebase/firestore/FirestoreDbWriter.java
  app/src/main/java/com/group80/uoftinder/firebase/realtime/ucChatMessageWriter.java
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_contacts.xml
Labels: documentation, refactor

#95 82 android testing
  app/build.gradle
  app/src/androidTest/java/com/group80/uoftinder/ChatSystemUnitTest.java
  app/src/androidTest/java/com/group80/uoftinder/ContactUnitTest.java
  app/src/androidTest/java/com/group80/uoftinder/CreateAccountTest.java
  app/src/androidTest/java/com/group80/uoftinder/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/group80/uoftinder/FilterViewUnitTest.java
  app/src/androidTest/java/com/group80/uoftinder/GenerateCompatibilityListUnitTest.java
  app/src/androidTest/java/com/group80/uoftinder/LoginActivityTest.java
  app/src/androidTest/java/com/group80/uoftinder/LogoutTest.java
  app/src/androidTest/java/com/group80/uoftinder/MatchInteractorUnitTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group80/uoftinder/create_account_use_case/CreateAccountActivity.java
  app/src/main/java/com/group80/uoftinder/feed/UserScoreFacade.java
  app/src/main/java/com/group80/uoftinder/feed/UserScoreSimChecker.java
  app/src/main/res/layout/activity_create_account.xml
  app/src/main/res/layout/recommendation_profile_display.xml
Labels: test, refactor

#97 Fixes #96: Teste for Realtime Database
  app/src/androidTest/java/com/group80/uoftinder/UserRealtimeDbFacadeUnitTest.java
Labels: test
