Repository CSC207-2022F-UofT/course-project-group-80, pull requests merged in 2022-11, with the labels that each got.

#21 Finish Chat System
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group80/uoftinder/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/HelloWorld.java
  app/src/main/java/com/group80/uoftinder/chat/Message.java
  app/src/main/java/com/group80/uoftinder/chat/MessageAdapter.java
  app/src/main/java/com/group80/uoftinder/firebase/realtime/RealtimeDbValueObserver.java
  app/src/main/java/com/group80/uoftinder/firebase/realtime/ucChatMessageWriter.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ImageStorageDbFacade.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/StorageDbDownloadable.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/StorageDbUploadable.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ucCompressedImageUploader.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ucDownloader.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ucImageDownloader.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ucImageUploader.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ucUploader.java
  app/src/main/res/drawable-v24/uoftinder_received_message_bubble.xml
  app/src/main/res/drawable/ic_baseline_account_circle_24.xml
  app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  app/src/main/res/drawable/ic_baseline_arrow_upward_24.xml
  app/src/main/res/drawable/uoftinder_message_edit_text_background.xml
  app/src/main/res/drawable/uoftinder_sent_message_bubble.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/hello_world.xml
  app/src/main/res/layout/uoftinder_received_nessage_layout.xml
  app/src/main/res/layout/uoftinder_sent_message_layout.xml
  build.gradle
Labels: enhancement

#39 Removed unnecessary files for storage database
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group80/uoftinder/DemoImageUploadActivity.java
  app/src/main/java/com/group80/uoftinder/firebase/storage/ctStorageController.java
  app/src/main/res/layout/activity_demo_image_upload.xml
Labels: bug

#37 Pull Request Template
  pull_request_template.md
Labels: documentation

#44 Fixes #43: Chat Feature Architectural Fix
  app/src/main/java/com/group80/uoftinder/ChatActivity.java
  app/src/main/java/com/group80/uoftinder/chat/MessageFactory.java
Labels: bug

#47 Fixes #16: GitHub Automated Testings
  .github/classroom/autograding.json
  .github/workflows/classroom.yml
  gradle_wrapper.sh
Labels: bug

#49 Fixes #45: Adapt to List<List<Integer>> for User.answers
  .idea/.name
  app/src/main/java/com/group80/uoftinder/CreateAccountView.java
  app/src/main/java/com/group80/uoftinder/UserAccountController.java
  app/src/main/java/com/group80/uoftinder/entities/User.java
  app/src/main/java/com/group80/uoftinder/feed/GenerateCompatibilityList.java
  app/src/main/java/com/group80/uoftinder/feed/UserScoreCalculator.java
  app/src/main/java/com/group80/uoftinder/feed/UserScoreFacade.java
  app/src/test/java/com/group80/uoftinder/FilterUseCaseUnitTest.java
  app/src/test/java/com/group80/uoftinder/UserScoreFacadeUnitTest.java
Labels: bug
